language: java
jdk: oraclejdk8
services:
  - docker
before_install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
addons:
  sonarcloud:
    organization: "deskubetor-github" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - docker build -t petclinic:$TRAVIS_BUILD_NUMBER .
  - curl https://cli-assets.heroku.com/install.sh | sh
  - heroku container:login
  - heroku container:push web --app coucou-petclinic
  - heroku container:release web --app coucou-petclinic
